baseURL = "https://hungry-mestorf-e314bb.netlify.app"
languageCode = "en-us"
title = "BurpyDave's Twiddlesticks"
theme = "hugo-clarity"  

[params]
figurePositionLabel = "Pic"
figurePositionShow = false
twitter = "burpydave"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokailight"
    tabWidth = 4